# Generated by Django 4.0.4 on 2022-04-23 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_customers',
            new_name='is_customer',
        ),
    ]
